#eureka :
  #instance:
   #client:
    #serviceUrl:
     #defaultZone: http://localhost:8761/

server:
  port: 8080
spring:
  application:
    name:  GatewayService
  cloud:
    gateway:
      routes:

        - id: UserService
          uri: http://localhost:8082/
          predicates:
            Path=/api/user/**
        - id: UserService
          uri: http://localhost:8082/
          predicates:
            Path=/api/auth/**
        - id: UserService
          uri: http://localhost:8082/
          predicates:
            Path=/api/roles/**
        - id: AddressService
          uri: http://localhost:8083/
          predicates:
            Path=/api/address/**
